#!/usr/bin/env python3
"""
Reader for `treasury-cache/dao_offchain_treasury.json`.

Canonical snapshot of the DAO's off-chain inventory. Regenerated by the
`tdg_inventory_management` Apps Script on every Telegram-logged inventory
movement and on a safety-net cron. Backs the `report_inventory_movement.html`
Warehouse-Manager + Inventory-Item dropdowns on the DApp.

Typical shell:

    python3 -m cache.treasury                                # pretty-print totals
    python3 -m cache.treasury --manager "Gary Teh"            # what Gary holds
    python3 -m cache.treasury --ledger AGL4                   # AGL4 ledger contents
    python3 -m cache.treasury --item ceremonial-cacao-500g    # where this SKU lives
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from cache._source import DataSource, GithubRawBackend
else:
    from ._source import DataSource, GithubRawBackend


RAW_URL = "https://raw.githubusercontent.com/TrueSightDAO/treasury-cache/main/dao_offchain_treasury.json"


@dataclass
class TreasuryCache:
    data: dict[str, Any] = field(default_factory=dict)
    source: DataSource = field(default_factory=lambda: GithubRawBackend(RAW_URL))

    @classmethod
    def fetch(cls, source: DataSource | None = None) -> "TreasuryCache":
        src = source or GithubRawBackend(RAW_URL)
        return cls(data=src.fetch(), source=src)

    # --- accessors -----------------------------------------------------------

    def generated_at(self) -> str:
        return str(self.data.get("generated_at", ""))

    def totals(self) -> dict[str, Any]:
        return dict(self.data.get("totals") or {})

    def items(self) -> list[dict[str, Any]]:
        return list(self.data.get("items") or [])

    def managers(self) -> list[dict[str, Any]]:
        return list(self.data.get("managers") or [])

    def ledgers(self) -> list[dict[str, Any]]:
        return list(self.data.get("ledgers") or [])

    def manager(self, name: str) -> dict[str, Any] | None:
        key = name.strip().lower()
        for m in self.managers():
            if str(m.get("name", "")).strip().lower() == key:
                return m
        return None

    def for_ledger(self, ledger_id: str) -> dict[str, Any] | None:
        key = ledger_id.strip().lower()
        for lg in self.ledgers():
            if str(lg.get("id") or lg.get("name") or "").strip().lower() == key:
                return lg
        return None

    def item(self, sku_or_name: str) -> dict[str, Any] | None:
        key = sku_or_name.strip().lower()
        for it in self.items():
            candidates = [it.get("sku"), it.get("name"), it.get("id")]
            if any(str(c).strip().lower() == key for c in candidates if c):
                return it
        return None


# ---------------------------------------------------------------- CLI


def _cli(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Read TrueSightDAO/treasury-cache/dao_offchain_treasury.json.")
    p.add_argument("--manager", help="Print one manager's holdings.")
    p.add_argument("--ledger", help="Print one ledger's contents (e.g. AGL4).")
    p.add_argument("--item", help="Print where a SKU / item name is held.")
    p.add_argument("--raw", action="store_true", help="Dump the full snapshot JSON.")
    args = p.parse_args(argv)

    tc = TreasuryCache.fetch()

    if args.raw:
        print(json.dumps(tc.data, indent=2))
        return 0
    if args.manager:
        rec = tc.manager(args.manager)
        if rec is None:
            print(f"No manager named {args.manager!r} in the snapshot.", file=sys.stderr)
            return 1
        print(json.dumps(rec, indent=2))
        return 0
    if args.ledger:
        rec = tc.for_ledger(args.ledger)
        if rec is None:
            print(f"No ledger matching {args.ledger!r} in the snapshot.", file=sys.stderr)
            return 1
        print(json.dumps(rec, indent=2))
        return 0
    if args.item:
        rec = tc.item(args.item)
        if rec is None:
            print(f"No item matching {args.item!r} in the snapshot.", file=sys.stderr)
            return 1
        print(json.dumps(rec, indent=2))
        return 0

    summary = {
        "generated_at": tc.generated_at(),
        "source": tc.data.get("source"),
        "schema_version": tc.data.get("schema_version"),
        "trigger": tc.data.get("trigger"),
        "totals": tc.totals(),
        "counts": {
            "items": len(tc.items()),
            "managers": len(tc.managers()),
            "ledgers": len(tc.ledgers()),
        },
    }
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(_cli())
